export const pbgs = {
    sheep: "gaia_herdable_sheep",
    wolf: "gaia_huntable_wolf",
    deer: "gaia_huntable_deer",
    boar: "gaia_huntable_boar",
    spearman: {
        english: "unit_spearman_4_eng",
        chinese: "unit_spearman_4_chi",
        french: "unit_spearman_4_fre",
        hre: "unit_spearman_4_hre",
        mongol: "unit_spearman_4_mon",
        rus: "unit_spearman_4_rus",
        sultanate: "unit_spearman_4_sul",
        abbasid: "unit_spearman_4_abb",

        abbasid_ha_01: "unit_spearman_4_abb_ha_01",
        chinese_ha_01: "unit_spearman_4_chi_ha_01",
        french_ha_01: "unit_spearman_4_fre_ha_01",
        hre_ha_01: "unit_spearman_4_hre_ha_01",
        japanese: "unit_spearman_4_jpn",
        byzantine: "unit_spearman_4_byz",
    },
    manAtArms: {
        english: "unit_manatarms_4_eng",
        chinese: "unit_manatarms_4_chi",
        french: "unit_manatarms_4_fre",
        hre: "unit_manatarms_4_hre",
        mongol: "unit_manatarms_4_mon",
        rus: "unit_manatarms_4_rus",
        sultanate: "unit_manatarms_4_sul",
        abbasid: "unit_manatarms_4_abb",

        abbasid_ha_01: "unit_manatarms_4_abb_ha_01",
        chinese_ha_01: "unit_manatarms_4_chi_ha_01",
        french_ha_01: "unit_manatarms_4_fre_ha_01",
        hre_ha_01: "unit_manatarms_4_hre_ha_01",
        japanese: "unit_manatarms_4_jpn",
        byzantine: "unit_manatarms_4_byz",
    },
    horseMan: {
        english: "unit_horseman_4_eng",
        chinese: "unit_horseman_4_chi",
        french: "unit_horseman_4_fre",
        hre: "unit_horseman_4_hre",
        mongol: "unit_horseman_4_mon",
        rus: "unit_horseman_4_rus",
        sultanate: "unit_horseman_4_sul",
        abbasid: "unit_horseman_4_abb",

        abbasid_ha_01: "unit_horseman_4_abb_ha_01",
        chinese_ha_01: "unit_horseman_4_chi_ha_01",
        french_ha_01: "unit_horseman_4_fre_ha_01",
        hre_ha_01: "unit_horseman_4_hre_ha_01",
        japanese: "unit_horseman_4_jpn",
        byzantine: "unit_horseman_4_byz",
    },
    mangonel: {
        english: "unit_mangonel_3_eng",
        chinese: "unit_mangonel_3_chi",
        french: "unit_mangonel_3_fre",
        hre: "unit_mangonel_3_hre",
        mongol: "unit_mangonel_3_mon",
        rus: "unit_mangonel_3_rus",
        sultanate: "unit_mangonel_3_sul",
        abbasid: "unit_mangonel_3_abb",

        abbasid_ha_01: "unit_mangonel_3_abb_ha_01",
        chinese_ha_01: "unit_mangonel_3_chi_ha_01",
        french_ha_01: "unit_mangonel_3_fre_ha_01",
        hre_ha_01: "unit_mangonel_3_hre_ha_01",
        japanese: "unit_mangonel_3_jpn",
        byzantine: "unit_mangonel_3_byz",
    },
}

export const sfxs = {
    roundFailure: "mus_stinger_landmark_objective_complete_fail",
    roundVictory: "Conquest_enemy_eliminated",
}
